sonar.organization=shiqing1412
sonar.projectKey=shiqing1412_sopra-fs26-group-17-client

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=./app
